Move telemetry to inline code for use in templates (#479)

diff --git a/eng/common/templates/steps/telemetry-end.yml b/eng/common/templates/steps/telemetry-end.yml
--- a/eng/common/templates/steps/telemetry-end.yml
+++ b/eng/common/templates/steps/telemetry-end.yml
@@ -3,8 +3,33 @@ parameters:
   helixType: 'undefined_defaulted_in_telemetry.yml'
 
 steps:
-- bash: /bin/bash ./telemetry/build/end.sh
-  workingDirectory: $(Build.SourcesDirectory)/eng/common
+- bash: |
+    if [ "$AGENT_JOBSTATUS" = "Succeeded" ] || [ "$AGENT_JOBSTATUS" = "PartiallySucceeded" ]; then
+      errorCount=0
+    else
+      errorCount=1
+    fi
+    warningCount=0
+
+    # create a temporary file for curl output
+    res=`mktemp`
+
+    curlResult=`
+      curl --silent --output $res\
+      -H 'Content-Type: application/json' \
+      -H 'X-Helix-Job-Token: $Helix_JobToken' \
+      -H 'Content-Length: 0' \
+      -X POST -G "https://helix.dot.net/api/2018-03-14/telemetry/job/build/$Helix_WorkItemId/finish" \
+      --data-urlencode "errorCount=$errorCount" \
+      --data-urlencode "warningCount=$warningCount"`
+    curlStatus=$?
+
+    if [ $curlStatus -ne 0 ]; then
+      echo "Failed to Send Build Finish information"
+      vstsLogOutput="vso[task.logissue type=error;sourcepath=templates/steps/telemetry-end.yml;code=1;]Failed to Send Build Finish information: $curlStatus"
+      echo "##$vstsLogOutput"
+      exit 1
+    fi
   displayName: Send Build End Telemetry
   env:
     # defined via VSTS variables in start-job.sh
@@ -12,11 +37,22 @@ steps:
     Helix_WorkItemId: $(Helix_WorkItemId)
   condition: and(always(), ne(variables['Agent.Os'], 'Windows_NT'))
 - powershell: |
-    ./telemetry/build/end.ps1
-    if ($LASTEXITCODE -ne 0) {
-      exit $LASTEXITCODE
+    if (($env:Agent_JobStatus -eq 'Succeeded') -or ($env:Agent_JobStatus -eq 'PartiallySucceeded')) {
+      $ErrorCount = 0
+    } else {
+      $ErrorCount = 1
     }
-  workingDirectory: $(Build.SourcesDirectory)/eng/common
+    $WarningCount = 0
+
+    try {
+      Invoke-RestMethod -Uri "https://helix.dot.net/api/2018-03-14/telemetry/job/build/$env:Helix_WorkItemId/finish?errorCount=$ErrorCount&warningCount=$WarningCount" -Method Post -ContentType "application/json" -Body "" `
+        -Headers @{ 'X-Helix-Job-Token'=$env:Helix_JobToken }
+    }
+    catch {
+      Write-Error $_
+      Write-Error $_.Exception
+      exit 1
+    }
   displayName: Send Build End Telemetry
   env:
     # defined via VSTS variables in start-job.ps1
diff --git a/eng/common/templates/steps/telemetry-start.yml b/eng/common/templates/steps/telemetry-start.yml
--- a/eng/common/templates/steps/telemetry-start.yml
+++ b/eng/common/templates/steps/telemetry-start.yml
@@ -11,8 +11,52 @@ steps:
     SecretsFilter: 'HelixApiAccessToken'
   condition: always()
 - bash: |
-    /bin/bash ./telemetry/start-job.sh --source "$Source" --type "$Type" --build "$Build" --queue-id "$QueueId" --attempt "$Attempt" -p "operatingSystem=$OperatingSystem" -p "configuration=$Configuration"
-  workingDirectory: $(Build.SourcesDirectory)/eng/common
+    # create a temporary file
+    jobInfo=`mktemp`
+
+    # write job info content to temporary file
+    cat > $jobInfo <<JobListStuff
+    {
+      "QueueId": "$QueueId",
+      "Source": "$Source",
+      "Type": "$Type",
+      "Build": "$Build",
+      "Attempt": "$Attempt",
+      "Properties": {
+        "operatingSystem": "$OperatingSystem",
+        "configuration": "$Configuration"
+      }
+    }
+    JobListStuff
+    
+    # create a temporary file for curl output
+    res=`mktemp`
+
+    curlResult=`
+      cat $jobInfo |\
+      curl --silent --output $res --write-out "%{http_code}" \
+      -H 'Content-Type: application/json' \
+      -X POST "https://helix.dot.net/api/2018-03-14/telemetry/job?access_token=$HelixApiAccessToken" -d @-`
+    curlStatus=$?
+
+    if [ $curlStatus -eq 0 ]; then
+      if [ $curlResult -gt 299 ] || [ $curlResult -lt 200 ]; then
+        curlStatus=$curlResult
+      fi
+    fi
+
+    # validate status of curl command
+    if [ $curlStatus -ne 0 ]; then
+      echo "Failed To Send Job Start information"
+      # We have to append the ## vso prefix or vso will pick up the command when it dumps the inline script into the shell
+      vstsLogOutput="vso[task.logissue type=error;sourcepath=telemetry/start-job.sh;code=1;]Failed to Send Job Start information: $curlStatus"
+      echo "##$vstsLogOutput"
+      exit 1
+    fi
+    
+    # Set the Helix_JobToken variable
+    export Helix_JobToken=`echo $curlResult | xargs echo` # Strip Quotes
+    echo "##vso[task.setvariable variable=Helix_JobToken;issecret=true;]$Helix_JobToken"
   displayName: Send Job Start Telemetry
   env:
     HelixApiAccessToken: $(HelixApiAccessToken)
@@ -25,8 +69,26 @@ steps:
     Configuration: ${{ parameters.buildConfig }}
   condition: and(always(), ne(variables['Agent.Os'], 'Windows_NT'))
 - bash: |
-    /bin/bash ./telemetry/build/start.sh --build-uri "$BuildUri"
-  workingDirectory: $(Build.SourcesDirectory)/eng/common
+    res=`mktemp`
+    curlResult=`
+      curl --silent --output $res\
+      -H 'Content-Type: application/json' \
+      -H "X-Helix-Job-Token: $Helix_JobToken" \
+      -H 'Content-Length: 0' \
+      -X POST -G "https://helix.dot.net/api/2018-03-14/telemetry/job/build" \
+      --data-urlencode "buildUri=$BuildUri"`
+    curlStatus=$?
+
+    # validate status of curl command
+    if [ $curlStatus -ne 0 ]; then
+      echo "Failed to Send Build Start information"
+      vstsLogOutput="vso[task.logissue type=error;sourcepath=telemetry/build/start.sh;code=1;]Failed to Send Build Start information: $curlStatus"
+      echo "##$vstsLogOutput"
+      exit 1
+    fi
+
+    export Helix_WorkItemId=`echo $curlResult | xargs echo` # Strip Quotes
+    echo "##vso[task.setvariable variable=Helix_WorkItemId]$Helix_WorkItemId"
   displayName: Send Build Start Telemetry
   env:
     BuildUri: $(System.TaskDefinitionsUri)$(System.TeamProject)/_build/index?buildId=$(Build.BuildId)&_a=summary
@@ -35,11 +97,22 @@ steps:
   condition: and(always(), ne(variables['Agent.Os'], 'Windows_NT'))
   
 - powershell: |
-    ./telemetry/start-job.ps1 -Source $env:Source -Type $env:Type -Build $env:Build -QueueId $env:QueueId -Attempt $env:Attempt -Properties @{ operatingSystem=$env:OperatingSystem; configuration=$env:Configuration } -Verbose
-    if ($LASTEXITCODE -ne 0) {
-      exit $LASTEXITCODE
+    $jobInfo = [pscustomobject]@{
+      QueueId=$env:QueueId;
+      Source=$env:Source;
+      Type=$env:Type;
+      Build=$env:Build;
+      Attempt=$env:Attempt;
+      Properties=[pscustomobject]@{ operatingSystem=$env:OperatingSystem; configuration=$env:Configuration };
     }
-  workingDirectory: $(Build.SourcesDirectory)/eng/common
+    
+    $jobInfoJson = $jobInfo | ConvertTo-Json
+
+    Write-Host "Job Info: $jobInfoJson"
+    $jobToken = Invoke-RestMethod -Uri "https://helix.dot.net/api/2018-03-14/telemetry/job?access_token=$($env:HelixApiAccessToken)" -Method Post -ContentType "application/json" -Body $jobInfoJson
+        
+    $env:Helix_JobToken = $jobToken
+    Write-Host "##vso[task.setvariable variable=Helix_JobToken;issecret=true;]$env:Helix_JobToken"
   displayName: Send Job Start Telemetry
   env:
     HelixApiAccessToken: $(HelixApiAccessToken)
@@ -52,11 +125,11 @@ steps:
     Configuration: ${{ parameters.buildConfig }}
   condition: and(always(), eq(variables['Agent.Os'], 'Windows_NT'))
 - powershell: |
-    ./telemetry/build/start.ps1 -BuildUri $env:BuildUri
-    if ($LASTEXITCODE -ne 0) {
-      exit $LASTEXITCODE
-    }
-  workingDirectory: $(Build.SourcesDirectory)/eng/common
+    $workItemId = Invoke-RestMethod -Uri "https://helix.dot.net/api/2018-03-14/telemetry/job/build?buildUri=$([Net.WebUtility]::UrlEncode($env:BuildUri))" -Method Post -ContentType "application/json" -Body "" `
+      -Headers @{ 'X-Helix-Job-Token'=$env:Helix_JobToken }
+  
+    $env:Helix_WorkItemId = $workItemId
+    Write-Host "##vso[task.setvariable variable=Helix_WorkItemId]$env:Helix_WorkItemId"
   displayName: Send Build Start Telemetry
   env:
     BuildUri: $(System.TaskDefinitionsUri)$(System.TeamProject)/_build/index?buildId=$(Build.BuildId)&_a=summary
